name: ddb_gui_qt5

on: [ push, pull_request ]

jobs:
  build_linux:
    name: Static linux
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
    - name: Install dependencies for Linux
      run: |
        apt-get -qq update
        apt-get install -y -qq qt5-default zlib1g-dev libdbus-1-dev \
          libxcb-xinput0 g++ wget zip unzip
    - name: Checkout for Linux
      uses: actions/checkout@v1
    - name: Fix library links
      run: chmod +x scripts/liblinks.sh; scripts/liblinks.sh
    - name: Build for Linux
      run: chmod +x scripts/build_static.sh; scripts/build_static.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: ddb_gui_qt5_linux-static.zip
  build_windows:
    name: CI for Windows
    runs-on: windows-latest
    steps:
    - name: Checkout for Windows
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain make tar unzip xz zip mingw-w64-x86_64-qt5-static
    - name: Build for Windows
      shell: msys2 {0}
      run: /mingw64/qt5-static/bin/qmake ; make ; mkdir -p plugins; mv release/*.dll plugins/ ; zip -r ddb_gui_qt5_windows_static.zip plugins/*.dll
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: ddb_gui_qt5_windows_static.zip